<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SixFourTwoThreeOneFive</name>
   <tag></tag>
   <elementGuidId>e55a020a-2b83-4320-9fa7-6870662d7790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vertical-list-container.mt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-tabpane-list']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SixFourTwoThreeOneFive&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5b32ab7-d90b-486d-b811-ca8495713364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vertical-list-container mt-4</value>
      <webElementGuid>337b1237-606c-4e3e-a99c-13cace7c1f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SixFourTwoThreeOneFive</value>
      <webElementGuid>742947ab-09ed-4cdc-a46d-bd88cc2661ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-tabpane-list&quot;)/div[@class=&quot;vertical-list-container mt-4&quot;]</value>
      <webElementGuid>d5240a44-9cd0-46be-8279-62c59bb13a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-tabpane-list']/div</value>
      <webElementGuid>10700155-3249-41a9-8841-1578053962c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sortable'])[2]/following::div[3]</value>
      <webElementGuid>da8468df-7060-4c65-82f0-d3b5671f343d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[7]</value>
      <webElementGuid>d9c40882-4020-4c92-829c-dd5191ea4e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>80b92ea1-97fe-423e-af03-c83ecc71d2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SixFourTwoThreeOneFive' or . = 'SixFourTwoThreeOneFive')]</value>
      <webElementGuid>b427bd28-b57b-4ab1-b23a-ab7625616dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
