<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FourTwoThreeOneFiveSix</name>
   <tag></tag>
   <elementGuidId>9af7c4dd-04d2-4f2a-b2b7-741f85c0501e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vertical-list-container.mt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-tabpane-list']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;FourTwoThreeOneFiveSix&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c084979a-e599-408a-b877-9aa059fdfc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vertical-list-container mt-4</value>
      <webElementGuid>419c41e9-8c3c-45a3-adab-a844993b7974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FourTwoThreeOneFiveSix</value>
      <webElementGuid>5937105e-28e3-4526-9a28-a993092c7453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-tabpane-list&quot;)/div[@class=&quot;vertical-list-container mt-4&quot;]</value>
      <webElementGuid>46f0e040-d54a-47dd-8b51-8fa43ce8e560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-tabpane-list']/div</value>
      <webElementGuid>6a93cab3-d565-4c28-a286-fa17c52c96c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sortable'])[2]/following::div[3]</value>
      <webElementGuid>9a7e677d-857b-40c4-95b2-53a27a0c0958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[7]</value>
      <webElementGuid>f2b293b1-edf5-43d1-8517-28f0b73252ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>74835673-7e37-43b7-a503-5d5f9bad8fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FourTwoThreeOneFiveSix' or . = 'FourTwoThreeOneFiveSix')]</value>
      <webElementGuid>4d72d8fa-d546-4ec3-849a-f0fdd92fec3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
